---
name: "Block Runner"

on:
  workflow_call:
    inputs:
      content:
        required: true
        type: string
      label:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Processing
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.1
      - uses: actions/cache@v4
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r "./_python/requirements.txt" --quiet
      - name: Check for new content
        run: python '_python/block_updater.py'
        env:
          content: ${{ inputs.content }}
          label: ${{ inputs.label }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          committer: GitHub Action <action@github.com>
          branch: "feat/config-from-issue-#${{ github.event.issue.number }}"
          delete-branch: true
          title: "Feat: ${{ github.event.issue.title}}"
          body: |
            Automatic PR for Config change: ${{ steps.title.outputs.title }}
            Closes #${{ github.event.issue.number }}
            reviewers: "${{ github.repository_owner }}"
            commit-message: "feat/commit-for-issue-#${{ github.event.issue.number }}"
