name: On Push Deploy
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v4
            - name: Call Deployment Workflow
              uses: ./.github/workflows/deployment.yml
