---
name: On Push Deploy
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Call Deployment Workflow
            uses: ./.github/workflows/deployment.yml
